@startuml
'https://plantuml.com/class-diagram

class main{
public static void main(String[] args)
}

class Student{
String email
String name
int phone
}
class Booking{
int bookingDate
int days
String comment
boolean bookingStatus
}
class Item{
String name
String itemDescription
}
class Room {
String name
String roomDescription
}

class StudentController{
viewStudent()
createStudent()
}

class BookingController{
viewAllItems()
viewAllBookedItems()
}

class BookingMapper{
getAllStudents()
getAllItems()
getBookedItems()

}

Student --> Booking
Booking <--  Item
Item <--  Room
Booking --> BookingController
BookingController --> BookingMapper



@enduml